const schedule = [
  {
    id: 967436,
    associationGroupePedagogiqueId: 3560104,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Analyse mathématique 1",
    matiereAr: "تحليل رياضي 1",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31337,
    plageHoraireLibelleFr: "09:30-11:00",
    plageHoraireHeureDebut: "09:30",
    plageHoraireHeureFin: "11:00",
    jourId: 1,
    jourCode: "DIM",
    jourLibelleFr: "Dimanche",
    jourLibelleAr: "Dimanche",
    enseignantId: 35884369,
    nomEnseignantLatin: "ASSALA",
    nomEnseignantArabe: "عسالة",
    prenomEnseignantLatin: "Aicha",
    prenomEnseignantArabe: "عائشة",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Analyse mathématique 1/2/Amphi 1/A. ASSALA",
  },
  {
    id: 967437,
    associationGroupePedagogiqueId: 3560105,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Economie générale ",
    matiereAr: "اقتصاد عام ",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31338,
    plageHoraireLibelleFr: "11:00-12:30",
    plageHoraireHeureDebut: "11:00",
    plageHoraireHeureFin: "12:30",
    jourId: 1,
    jourCode: "DIM",
    jourLibelleFr: "Dimanche",
    jourLibelleAr: "Dimanche",
    enseignantId: 38881125,
    nomEnseignantLatin: "ATIL",
    nomEnseignantArabe: "عطيل",
    prenomEnseignantLatin: "Assia",
    prenomEnseignantArabe: "اسيا",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Economie générale /2/Amphi 1/A. ATIL",
  },
  {
    id: 967438,
    associationGroupePedagogiqueId: 3560106,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Algèbre",
    matiereAr: " الجبر",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31336,
    plageHoraireLibelleFr: "08:00-09:30",
    plageHoraireHeureDebut: "08:00",
    plageHoraireHeureFin: "09:30",
    jourId: 3,
    jourCode: "MAR",
    jourLibelleFr: "Mardi",
    jourLibelleAr: "Mardi",
    enseignantId: 35884361,
    nomEnseignantLatin: "YESSAAD  MOKHTARI",
    nomEnseignantArabe: "يسعد مختاري",
    prenomEnseignantLatin: "Sabah",
    prenomEnseignantArabe: "صباح",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Algèbre/2/Amphi 1/S. YESSAAD  MOKHTARI",
  },
  {
    id: 967439,
    associationGroupePedagogiqueId: 3560107,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Comptabilité financière 1",
    matiereAr: "محاسبة مالية 1",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31336,
    plageHoraireLibelleFr: "08:00-09:30",
    plageHoraireHeureDebut: "08:00",
    plageHoraireHeureFin: "09:30",
    jourId: 1,
    jourCode: "DIM",
    jourLibelleFr: "Dimanche",
    jourLibelleAr: "Dimanche",
    enseignantId: 35882075,
    nomEnseignantLatin: "BENCHIKH LEHOCINE ",
    nomEnseignantArabe: "بن الشيخ الحسين",
    prenomEnseignantLatin: "Ahmed",
    prenomEnseignantArabe: " احمد",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance:
      "CM/Comptabilité financière 1/2/Amphi 1/A. BENCHIKH LEHOCINE ",
  },
  {
    id: 967440,
    associationGroupePedagogiqueId: 3560109,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Fondement du droit 1",
    matiereAr: "أسس القانون 1",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8312,
    refLieuDesignation: "Amphi 2",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31340,
    plageHoraireLibelleFr: "15:30-17:00",
    plageHoraireHeureDebut: "15:30",
    plageHoraireHeureFin: "17:00",
    jourId: 3,
    jourCode: "MAR",
    jourLibelleFr: "Mardi",
    jourLibelleAr: "Mardi",
    enseignantId: 38881145,
    nomEnseignantLatin: "DJESAS",
    nomEnseignantArabe: "جصاص",
    prenomEnseignantLatin: "Rajaa",
    prenomEnseignantArabe: "رجاء",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Fondement du droit 1/2/Amphi 2/R. DJESAS",
  },
  {
    id: 967441,
    associationGroupePedagogiqueId: 3560101,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Philosophie ",
    matiereAr: "فلسفة ",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8312,
    refLieuDesignation: "Amphi 2",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31339,
    plageHoraireLibelleFr: "14:00-15:30",
    plageHoraireHeureDebut: "14:00",
    plageHoraireHeureFin: "15:30",
    jourId: 3,
    jourCode: "MAR",
    jourLibelleFr: "Mardi",
    jourLibelleAr: "Mardi",
    enseignantId: 35884363,
    nomEnseignantLatin: "BELKACEMI",
    nomEnseignantArabe: "بلقاسمي",
    prenomEnseignantLatin: "Aida",
    prenomEnseignantArabe: "عايدة",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Philosophie /2/Amphi 2/A. BELKACEMI",
  },
  {
    id: 967442,
    associationGroupePedagogiqueId: 3560102,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Informatique 1",
    matiereAr: "إعلام آلي 1",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31338,
    plageHoraireLibelleFr: "11:00-12:30",
    plageHoraireHeureDebut: "11:00",
    plageHoraireHeureFin: "12:30",
    jourId: 3,
    jourCode: "MAR",
    jourLibelleFr: "Mardi",
    jourLibelleAr: "Mardi",
    enseignantId: 35884370,
    nomEnseignantLatin: "NEMOUCHI",
    nomEnseignantArabe: "نموشي",
    prenomEnseignantLatin: "Soulef",
    prenomEnseignantArabe: "سلاف",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Informatique 1/2/Amphi 1/S. NEMOUCHI",
  },
  {
    id: 967443,
    associationGroupePedagogiqueId: 3560103,
    groupePedagogiqueId: 590794,
    periodeId: 16,
    sectionId: null,
    groupe: "2",
    matiere: "Statistiques descriptives ",
    matiereAr: "الإحصاء الوصفي ",
    ap: "CM",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 8314,
    refLieuDesignation: "Amphi 1",
    refLieuTypeLibelleLongFr: "Amphi",
    plageHoraireId: 31337,
    plageHoraireLibelleFr: "09:30-11:00",
    plageHoraireHeureDebut: "09:30",
    plageHoraireHeureFin: "11:00",
    jourId: 3,
    jourCode: "MAR",
    jourLibelleFr: "Mardi",
    jourLibelleAr: "Mardi",
    enseignantId: 35882080,
    nomEnseignantLatin: "Ghouar",
    nomEnseignantArabe: "غوار",
    prenomEnseignantLatin: " Ahlem",
    prenomEnseignantArabe: "احلام",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "CM/Statistiques descriptives /2/Amphi 1/ . GHOUAR",
  },
  {
    id: 967468,
    associationGroupePedagogiqueId: 3560181,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Analyse mathématique 1",
    matiereAr: "تحليل رياضي 1",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9562,
    refLieuDesignation: "Salle 2\t",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31337,
    plageHoraireLibelleFr: "09:30-11:00",
    plageHoraireHeureDebut: "09:30",
    plageHoraireHeureFin: "11:00",
    jourId: 4,
    jourCode: "MER",
    jourLibelleFr: "Mercredi",
    jourLibelleAr: "Mercredi",
    enseignantId: 35884368,
    nomEnseignantLatin: "BERKANE",
    nomEnseignantArabe: "بركان",
    prenomEnseignantLatin: "Ali",
    prenomEnseignantArabe: "علي",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Analyse mathématique 1/4/Salle 2\t/A. BERKANE",
  },
  {
    id: 967469,
    associationGroupePedagogiqueId: 3560182,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Economie générale ",
    matiereAr: "اقتصاد عام ",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9562,
    refLieuDesignation: "Salle 2\t",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31338,
    plageHoraireLibelleFr: "11:00-12:30",
    plageHoraireHeureDebut: "11:00",
    plageHoraireHeureFin: "12:30",
    jourId: 4,
    jourCode: "MER",
    jourLibelleFr: "Mercredi",
    jourLibelleAr: "Mercredi",
    enseignantId: 38878467,
    nomEnseignantLatin: "benaissa",
    nomEnseignantArabe: "بن عيسى",
    prenomEnseignantLatin: "ilhem",
    prenomEnseignantArabe: "الهام",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Economie générale /4/Salle 2\t/I. BENAISSA",
  },
  {
    id: 967470,
    associationGroupePedagogiqueId: 3560183,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Algèbre",
    matiereAr: " الجبر",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9010,
    refLieuDesignation: "Salle 4",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31336,
    plageHoraireLibelleFr: "08:00-09:30",
    plageHoraireHeureDebut: "08:00",
    plageHoraireHeureFin: "09:30",
    jourId: 5,
    jourCode: "JEU",
    jourLibelleFr: "Jeudi",
    jourLibelleAr: "Jeudi",
    enseignantId: 35884361,
    nomEnseignantLatin: "YESSAAD  MOKHTARI",
    nomEnseignantArabe: "يسعد مختاري",
    prenomEnseignantLatin: "Sabah",
    prenomEnseignantArabe: "صباح",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Algèbre/4/Salle 4/S. YESSAAD  MOKHTARI",
  },
  {
    id: 967471,
    associationGroupePedagogiqueId: 3560184,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Comptabilité financière 1",
    matiereAr: "محاسبة مالية 1",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9010,
    refLieuDesignation: "Salle 4",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31337,
    plageHoraireLibelleFr: "09:30-11:00",
    plageHoraireHeureDebut: "09:30",
    plageHoraireHeureFin: "11:00",
    jourId: 5,
    jourCode: "JEU",
    jourLibelleFr: "Jeudi",
    jourLibelleAr: "Jeudi",
    enseignantId: 35884395,
    nomEnseignantLatin: "CHEMMAM",
    nomEnseignantArabe: "شمام",
    prenomEnseignantLatin: "Ouafa",
    prenomEnseignantArabe: "وفاء",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Comptabilité financière 1/4/Salle 4/O. CHEMMAM",
  },
  {
    id: 967472,
    associationGroupePedagogiqueId: 3560185,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Français 1",
    matiereAr: "فرنسية 1",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9568,
    refLieuDesignation: "Salle 10",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31339,
    plageHoraireLibelleFr: "14:00-15:30",
    plageHoraireHeureDebut: "14:00",
    plageHoraireHeureFin: "15:30",
    jourId: 4,
    jourCode: "MER",
    jourLibelleFr: "Mercredi",
    jourLibelleAr: "Mercredi",
    enseignantId: 35882079,
    nomEnseignantLatin: "MADOUI",
    nomEnseignantArabe: "مضوي",
    prenomEnseignantLatin: "Sandra",
    prenomEnseignantArabe: "صندرة",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Français 1/4/Salle 10/S. MADOUI",
  },
  {
    id: 967473,
    associationGroupePedagogiqueId: 3560186,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Anglais 1",
    matiereAr: "إنجليزية 1",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9568,
    refLieuDesignation: "Salle 10",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31340,
    plageHoraireLibelleFr: "15:30-17:00",
    plageHoraireHeureDebut: "15:30",
    plageHoraireHeureFin: "17:00",
    jourId: 4,
    jourCode: "MER",
    jourLibelleFr: "Mercredi",
    jourLibelleAr: "Mercredi",
    enseignantId: 35882069,
    nomEnseignantLatin: "BENGHOMRANI",
    nomEnseignantArabe: "بن غمراني",
    prenomEnseignantLatin: "Naziha",
    prenomEnseignantArabe: "نزيهة",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Anglais 1/4/Salle 10/N. BENGHOMRANI",
  },
  {
    id: 967474,
    associationGroupePedagogiqueId: 4363500,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Informatique 1",
    matiereAr: "إعلام آلي 1",
    ap: "TP",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 13272,
    refLieuDesignation: "Labo 2",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31336,
    plageHoraireLibelleFr: "08:00-09:30",
    plageHoraireHeureDebut: "08:00",
    plageHoraireHeureFin: "09:30",
    jourId: 4,
    jourCode: "MER",
    jourLibelleFr: "Mercredi",
    jourLibelleAr: "Mercredi",
    enseignantId: 38303813,
    nomEnseignantLatin: "RAIS",
    nomEnseignantArabe: "رايس",
    prenomEnseignantLatin: "MOHAMED SABER",
    prenomEnseignantArabe: "محمد صابر",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TP/Informatique 1/4/Labo 2/M. RAIS",
  },
  {
    id: 967475,
    associationGroupePedagogiqueId: 3560180,
    groupePedagogiqueId: 590802,
    periodeId: 16,
    sectionId: 590794,
    groupe: "4",
    matiere: "Statistiques descriptives ",
    matiereAr: "الإحصاء الوصفي ",
    ap: "TD",
    emploiId: 19384,
    enseignantNom: null,
    enseignantPrenom: null,
    refLieuId: 9010,
    refLieuDesignation: "Salle 4",
    refLieuTypeLibelleLongFr: "Salle",
    plageHoraireId: 31338,
    plageHoraireLibelleFr: "11:00-12:30",
    plageHoraireHeureDebut: "11:00",
    plageHoraireHeureFin: "12:30",
    jourId: 5,
    jourCode: "JEU",
    jourLibelleFr: "Jeudi",
    jourLibelleAr: "Jeudi",
    enseignantId: 35884485,
    nomEnseignantLatin: "MERADJI",
    nomEnseignantArabe: "مراجي",
    prenomEnseignantLatin: "Asma",
    prenomEnseignantArabe: "اسماء",
    lieuDisponible: null,
    enseignantDisponible: null,
    groupeDisponible: null,
    libelleSeance: "TD/Statistiques descriptives /4/Salle 4/A. MERADJI",
  },
]

export default function WeeklyTimetable() {
  const groupByDay = (schedule: any) => {
    const days = [0, 1, 2, 3, 4, 5]
    const grouped = {} as any

    days.forEach((dayId: any) => {
      grouped[dayId] = schedule.filter((seance: any) => seance.jourId === dayId)
    })

    return grouped
  }

  const extractTimeSlots = (schedule: { plageHoraireLibelleFr: string }[]) => {
    const timeSlots: string[] = []
    schedule.forEach((seance) => {
      const timeSlot = seance.plageHoraireLibelleFr
      if (!timeSlots.includes(timeSlot)) {
        timeSlots.push(timeSlot)
      }
    })
    return timeSlots.sort()
  }
  // Group the schedule by day of the week (using jourId)
  const groupedSchedule = groupByDay(schedule)

  // Define time slots (you can adjust these to fit your needs)
  const timeSlots = extractTimeSlots(schedule)

  // Map jourId to Day names, skipping Friday (jourId 5)
  const dayMap = {
    0: "Samedi",
    1: "Dimanche",
    2: "Lundi",
    3: "Mardi",
    4: "Mercredi",
    5: "Jeudi",
  }

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4 text-center">Weekly Timetable</h1>
      <div className="overflow-x-auto">
        <table className="min-w-full table-auto border-collapse border border-gray-300">
          <thead>
            <tr className="bg-gray-200">
              <th className="p-2 border border-gray-300 w-1/6 text-center">
                Time
              </th>
              {Object.entries(dayMap).map(([dayId, dayName]) => (
                <th
                  key={dayId}
                  className="p-2 border border-gray-300 w-1/6 text-center"
                >
                  {dayName}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {timeSlots.map((slot: any) => (
              <tr key={slot}>
                <td className="p-2 border border-gray-300 text-center">
                  {slot}
                </td>
                {Object.keys(dayMap).map((dayId) => (
                  <td
                    key={dayId}
                    className="p-2 border border-gray-300 text-center"
                  >
                    {groupedSchedule[dayId]
                      .filter(
                        (seance: any) => seance.plageHoraireLibelleFr === slot,
                      )
                      .map((seance: any) => (
                        <div
                          key={seance.id}
                          className="text-sm flex justify-between"
                        >
                          <strong>{seance.matiere}</strong>
                          <span>{seance.ap}</span>
                        </div>
                      ))}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
